baseURL = "https://pabloloveshot.github.io/"
languageCode = "ko-kr"
title = "Pablo Love Shot"
theme = "PaperMod"

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
title = "PabloBlog"
description = "Pablo's Personal Blog"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = "PabloBlog"
Content = "Pablo의 개인 블로그입니다."

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/archives/"
weight = 20

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 30
